import avautuvat_sotilassaaret from '~/assets/avautuvat-sotilassaaret.jpg';
import kutsuntaliite from '~/assets/kutsuntaliite-2014.jpg';
import kaupunkisotilas_ja_siviili from '~/assets/kaupunkisotilas-ja-siviili.jpg';
import yhteiskuntaa_karkuun from '~/assets/yhteiskuntaa-karkuun-kiven-sisaan.jpg';

const articles: Article[] = [
  {
    platform: 'web',
    types: ['data'],
    title:
      'Massiivinen Tripla kiilaa koollaan Suomen ostoskeitaiden kärkikolmikkoon ja on pian lähin kauppakeskus yli 100 000:lle joukkoliikenteen käyttäjälle',
    url: 'https://yle.fi/uutiset/3-11016106',
    imageId: '39-5893575d762b795ff2f',
    publishedDate: '14.10.2019',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data'],
    title:
      'Vanhusten palvelutaloihin tehdään vain harvoin yllätystarkastuksia – katso, kuinka sinun kuntasi valvoo ikäihmisten oloja',
    url: 'https://yle.fi/uutiset/3-10734160',
    imageId: '13-3-10731896',
    publishedDate: '24.4.2019',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Äärioikeistolainen lapuanliike muilutti, murhasi ja terrorisoi – Jaakko Kosola on kuuluisaa sukua ja kantaa historian arpia mukanaan',
    url: 'https://yle.fi/uutiset/3-11068956',
    imageId: '39-6237985df8ea2ff41a3',
    publishedDate: '21.12.2019',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      '"Mitä nää uudet sanat on? Yhtäkkii mä käytän niit" – tämän jutun äikän ope haluaisi sinulta kieltää, mutta lukee itse salaa',
    url: 'https://yle.fi/uutiset/3-11089578',
    imageId: '13-3-11103569',
    publishedDate: '8.12.2019',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data'],
    title:
      '"Perhe on vähän vanhanaikainen haave" – Ylen kone näyttää, kuinka moni ikäisesi asuu yksin',
    url: 'https://yle.fi/uutiset/3-11088126',
    imageId: '39-6160635ddd28eb92bf2',
    publishedDate: '28.11.2019',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data', 'feature'],
    title:
      'Suomessa ajetaan vuosittain tuhansia hirvikolareita – katso kartasta, millä teillä pelti rytisee',
    url: 'https://yle.fi/uutiset/3-10946241',
    imageId: '13-3-10947472',
    publishedDate: '4.9.2019',
    publisher: 'Yle',
    roles: ['coder', 'writer'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Kaksoismurhaajan jahtaaminen oli viedä poliisin epätoivoon – suohon kätketty salaisuus raottuu Tulilahden tutkintamateriaalista',
    url: 'https://yle.fi/uutiset/3-10881289',
    imageId: '13-3-10883209',
    publishedDate: '19.7.2019',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Onko Helsingissä pian yhtä kuuma kuin Montenegrossa? Katso, miten suomalaiset kaupungit lämpenevät vuoteen 2080 mennessä',
    url: 'https://yle.fi/uutiset/3-10346334',
    imageId: '13-3-10374675',
    publishedDate: '1.9.2018',
    publisher: 'Yle',
    roles: ['writer'],
  },
  {
    platform: 'web',

    title:
      'Donald Trumpin presidenttikausi ei ole vakuuttanut suomalaisia – vain ani harva uskoo Trumpin tehneen maailmasta turvallisemman',
    url: 'https://yle.fi/uutiset/3-10277828',
    imageId: '13-3-10287820',
    publishedDate: '9.7.2018',
    publisher: 'Yle',
    roles: ['writer'],
  },
  {
    platform: 'web',

    title:
      'Hyvätapainen televisiotähti vai kovasanainen kiinteistöhai? – tällainen vieras Donald Trump saattaisi olla, jos hän astuisi sinun kotiisi',
    url: 'https://yle.fi/uutiset/3-10289879',
    imageId: '13-3-10302881',
    publishedDate: '15.7.2018',
    publisher: 'Yle',
    roles: ['writer'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Suomalaisten lempikarkin hämmentävä ristiriita – salmiakki on terveellinen, mutta samaan aikaan terveydelle vaarallinen herkku',
    url: 'https://yle.fi/uutiset/3-10805175',
    imageId: '13-3-10805719',
    publishedDate: '2.6.2019',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data'],
    title:
      'Katso, mistä löytyvät vaarallisimmat tiet ja kuumapäisimmät kuskit – "Kaikilla on raja, jonka jälkeen kiehahtaa yli"',
    url: 'https://yle.fi/uutiset/3-11116844',
    imageId: '39-6297195e1845bd6f04b',
    publishedDate: '11.1.2020',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',

    title:
      'Näin Trumpin ja Kimin tapaaminen huomioitiin Pohjois-Korean mediassa – pohjoiskorealaiset seurasivat lähetystä Pjongjangin rautatieasemalla',
    url: 'https://yle.fi/uutiset/3-10249603',
    imageId: '13-3-10249645',
    publishedDate: '12.6.2018',
    publisher: 'Yle',
    roles: ['writer'],
  },
  {
    platform: 'web',

    title:
      'Purkutuomion saanut kerrostalo teki viimeisen palveluksensa – muuttui värikkääksi festaripaikaksi',
    url: 'https://yle.fi/uutiset/3-8212940',
    imageId: '13-3-8213008',
    publishedDate: '9.8.2015',
    publisher: 'Yle',
    roles: ['writer'],
  },
  {
    platform: 'web',

    title:
      'Thaimaassa luolasta pelastetut pojat kertovat, kuinka he joivat sadevettä tippukivistä ja yrittivät kaivaa tietään ulos – Yle seurasi hetki hetkeltä',
    url: 'https://yle.fi/uutiset/3-10310825',
    imageId: '13-3-10311352',
    publishedDate: '18.7.2018',
    publisher: 'Yle',
    roles: ['writer'],
  },
  {
    platform: 'web',

    title:
      'Unkari muuttaa perustuslakiaan – uusi laki tekee turvapaikanhakijoiden auttamisesta rangaistavaa',
    url: 'https://yle.fi/uutiset/3-10266522',
    imageId: '13-3-10266670',
    publishedDate: '20.6.2018',
    publisher: 'Yle',
    roles: ['writer'],
  },
  {
    platform: 'web',

    title: 'Mustikka kukkii parhaiten 22 vuoteen – sadosta kypsymässä hyvin runsas',
    url: 'https://yle.fi/uutiset/3-8106280',
    imageId: '13-3-6794021',
    publishedDate: '26.6.2015',
    publisher: 'Yle',
    roles: ['writer'],
  },
  {
    platform: 'web',

    title: 'Perussuomalaisten Sebastian Tynkkynen: BB-tähdestä puolueen varapuheenjohtajaksi',
    url: 'https://yle.fi/uutiset/3-8213407',
    imageId: '13-3-8213448',
    publishedDate: '9.8.2015',
    publisher: 'Yle',
    roles: ['writer'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Tämä on kertomus saamenpuvuista – aviomies halusi säpikkäisiinsä vihreää, sillä vaimo on kotoisin Lemmenjoen mäntymetsästä – Gákti čatná olbmuid oktii: vihtta gáktemuitalusa',
    url: 'https://yle.fi/uutiset/3-11191637',
    imageId: '39-6391335e3abe44dee40',
    publishedDate: '5.2.2020',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Avantouinti on nyt niin suosittua, että jäihin pitää jonottaa – katso, miten liha kangistuu ja nahka höyryää Suomen vilkkaimmalla avannolla',
    url: 'https://yle.fi/uutiset/3-11192805',
    imageId: '39-6381075e38278eba158',
    publishedDate: '8.2.2020',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data'],
    title:
      'Kuoppaisella tiellä ambulanssikyytikin kestää kauemmin – Suomessa on tuhansia kilometrejä huonoja teitä, katso kartasta oman kuntasi tilanne',
    url: 'https://yle.fi/uutiset/3-11228875',
    imageId: '39-6474095e57711235dd1',
    publishedDate: '4.3.2020',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'print',
    title:
      'Avautuvat sotilassaaret – Puolustusvoimien vuokralaisuus sotilassaarilla päättyy. Miltä saarten tulevaisuus näyttää?',
    url: 'https://drive.google.com/file/d/1qbTA0E3qbq5oDLrAxuo-_cNpJsqZMqxa/view?usp=sharing',
    imageId: avautuvat_sotilassaaret.src,
    publishedDate: '26.6.2014',
    publisher: 'Ruotuväki',
    roles: ['writer'],
  },
  {
    platform: 'print',

    title: 'Kutsuntaliite 2014 – Kutsuntojen kautta asevelvollisuuden matkalle',
    url: 'https://drive.google.com/file/d/15uCUsIVqhioFFdOI7-bm6ahZqHcm97TL/view?usp=sharing',
    imageId: kutsuntaliite.src,
    publishedDate: '17.7.2014',
    publisher: 'Ruotuväki',
    roles: ['producer', 'writer'],
  },
  {
    platform: 'print',

    title: 'Kaupunkisotilas & siviili',
    url: 'https://drive.google.com/file/d/1PQSTiNn24AFKnxosjzPy37TScCqIwDjt/view?usp=sharing',
    imageId: kaupunkisotilas_ja_siviili.src,
    publishedDate: '3.4.2014',
    publisher: 'Ruotuväki',
    roles: ['writer'],
  },
  {
    platform: 'print',

    title: 'Yhteiskuntaa karkuun kiven sisään',
    url: 'https://drive.google.com/file/d/1yg0uMZFYjl6qvSv-ZxFdN_qMgwMOKglo/view?usp=sharing',
    imageId: yhteiskuntaa_karkuun.src,
    publishedDate: '15.1.2015',
    publisher: 'Utain',
    roles: ['writer'],
  },
  {
    platform: 'web',

    title:
      'Jos koronatilanne ahdistaa, on hyvä hetki pysähtyä miettimään omaa elämää – testaa tästä, kuinka onnellinen olet',
    url: 'https://yle.fi/uutiset/3-11263263',
    imageId: '39-6556815e7470b15a6e1',
    publishedDate: '21.3.2020',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data'],
    title: 'Ylen selvitys: Liikennemäärä Uudenmaan rajoilla on jo merkittävästi vähentynyt',
    url: 'https://yle.fi/uutiset/3-11277639',
    imageId: '39-6566855e78b2ecf3b81',
    publishedDate: '26.3.2020',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Mikä on surumuna, mitä kertoo munan koodi ja onko vapaa kana vapaa? Suomalainen syö 12 kiloa munia vuodessa ja siksi on hyvä tietää, mitä syö',
    url: 'https://yle.fi/uutiset/3-11290114',
    imageId: '13-3-11290540',
    publishedDate: '4.4.2020',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data'],
    title:
      'Tulipalo saa yleensä alkunsa liedeltä, mutta vanha vitsaus aiheuttaa edelleen eniten kuolemia – katso kartasta, missä ja miten rakennukset palavat Tampereella',
    url: 'https://yle.fi/uutiset/3-11325984',
    imageId: '13-3-11341810',
    publishedDate: '8.5.2020',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Ylen selvitys: toimeentulotuen uudistus on epäonnistunut kaikkein heikompiosaisten kohdalla – lue Jaron, Sirpan, Ilmin ja Johannan tarinat köyhyydestä',
    url: 'https://yle.fi/uutiset/3-11351353',
    imageId: '13-3-11350850',
    publishedDate: '19.5.2020',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',

    title:
      'Kysyimme, mitä on hyvä elämä ja näin suomalaiset vastasivat – testaa, ovatko sinulle tärkeät asiat tärkeitä myös muille',
    url: 'https://yle.fi/uutiset/3-11360661',
    imageId: '39-5696215cfe5f8d5cfc3',
    publishedDate: '22.5.2020',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data'],
    title:
      'Henkirikokset rajussa kasvussa tänä keväänä, poliisi: "Ei ole kontrollia, minne veitsen isku päätyy" – katso kartalta 2000-luvun Suomen väkivaltaisimmat paikat',
    url: 'https://yle.fi/uutiset/3-11383347',
    imageId: '13-3-11405609',
    publishedDate: '17.6.2020',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      '35 000 miestä rakensi Suomen halki valtavan rakennelman, joka kestää vaikka tykkitulen – katso, miten Salpalinja syntyi ja mitä siitä on jäljellä',
    url: 'https://yle.fi/uutiset/3-11403518',
    imageId: '13-3-11408424',
    publishedDate: '21.6.2020',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Nyt on paras hetki rakentaa muodikas ötökkähotelli, mutta asuuko niissä oikeasti hyönteisiä? – Katso, millaisia asukkaita hotellissamme majailee',
    url: 'https://yle.fi/uutiset/3-11417908',
    imageId: '13-3-11454139',
    publishedDate: '23.7.2020',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data', 'feature'],
    title:
      'Katso, kuinka vihreä kotikuntasi on – vertasimme Suomen kaikkia kuntia viidellä eri kriteerillä, ja mallioppilaat erottuvat joukosta',
    url: 'https://yle.fi/uutiset/3-11504485',
    imageId: '13-3-11513638',
    publishedDate: '3.9.2020',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',

    title:
      'Saaʹmi ouddoummuvaali võboršeǩ-kueiʹtes ǩeâsttâʹlle vuäʹmm tååimast – Kolttien luottamusmiesvaalin ehdokaskaksikko kisaa ikivanhasta luottamustoimesta',
    url: 'https://yle.fi/uutiset/3-11516665',
    imageId: '39-7124345f477ebe917ac',
    publishedDate: '3.9.2020',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Moni meistä ajattelee kuin Jari Matikainen: Biojätteen lajittelu on liian hankalaa – siksi valtava määrä ruokaa poltetaan sekajätteen mukana',
    url: 'https://yle.fi/uutiset/3-11533305',
    imageId: '39-7188865f605bb2a1dd1',
    publishedDate: '21.9.2020',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data'],
    title:
      'Katso kartasta, mitkä rikollisorganisaatiot kokoontuvat kotikulmillasi – KRP: jengitilanne voimakkaassa muutoksessa United Brotherhoodin väliaikaisen toimintakiellon vuoksi',
    url: 'https://yle.fi/uutiset/3-11542665',
    imageId: '14-svyle-499531971e593882',
    publishedDate: '26.9.2020',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      '"Nainen ei saa olla seksikäs, mies ei saa itkeä" – 1 200 opiskelijaa vastasi, miten sukupuolinormit vaikuttavat heidän elämäänsä',
    url: 'https://yle.fi/uutiset/3-11570381',
    imageId: '13-3-11580957',
    publishedDate: '13.10.2020',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['game'],
    title:
      'Mitä teet, kun pieni koululainen kertoo nähneensä pornoa kaverin puhelimesta? Testaa pelissä, miten selviydytte vaikeasta paikasta yhdessä',
    url: 'https://yle.fi/uutiset/3-11603623',
    imageId: '13-3-11623822',
    publishedDate: '9.11.2020',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Ylen toimittaja soluttautui hämärille eläinmarkkinoille – koirasusien kasvatus ja myynti kiellettiin lailla, mutta kauppa käy yhä',
    url: 'https://yle.fi/uutiset/3-11689345',
    imageId: '39-7524315fd0ca55e7dcc',
    publishedDate: '10.12.2020',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Kun Mannerheim halusi viettää löhölomaa, hän lähti metsästysmajalleen, jossa ei koskaan metsästetty – tutustu Marskin majaan',
    url: 'https://yle.fi/uutiset/3-11688673',
    imageId: '13-3-11689391',
    publishedDate: '11.12.2020',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data'],
    title:
      'Suomalaisten ruokavalio kuuluu EU:n pahiksiin – kokeile Ylen ruokakoneella, miten lounaalla tekemäsi valinnat vaikuttavat ympäristöön',
    url: 'https://yle.fi/uutiset/3-11699920',
    imageId: '13-3-11714060',
    publishedDate: '1.1.2021',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Moni on tietämättään säilyttänyt dna-tutkijan aarretta piironginlaatikossa – suomenhevosen alkuperää selvitetään vanhojen näytteiden avulla',
    url: 'https://yle.fi/uutiset/3-11772583',
    imageId: '39-770101601be266175b9',
    publishedDate: '7.2.2021',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data'],
    title:
      'Yle selvitti: Kunnat säästivät miljoonia euroja kulttuurirahoista samalla kun korona vei taiteilijoiden työt – katso kotikuntasi tilanne',
    url: 'https://yle.fi/uutiset/3-11807638',
    imageId: '13-3-11811007',
    publishedDate: '28.2.2021',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Hiki valui otsalta, kun Jasmin Muqolli näki äänisaaliinsa – kuntapolitiikka opetti ensikertalaiselle paljon, mutta tuotti myös pettymyksiä',
    url: 'https://yle.fi/uutiset/3-11795312',
    imageId: '39-780611603f94594f14e',
    publishedDate: '6.3.2021',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',

    title:
      'Selvitimme kaikissa Manner-Suomen kunnissa, mikä niissä puhuttaa vaalien alla – kuuntele Kuntarundi-keskustelu omasta kotikunnastasi',
    url: 'https://yle.fi/uutiset/3-11916600',
    imageId: '39-8028036093a317a6f11',
    publishedDate: '11.5.2021',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data'],
    title:
      'Selvitimme kaikkien Manner-Suomen kuntien nykykunnon ja tulevaisuuden näkymät – katso kotikuntasi tilanne Ylen Kuntatutkasta',
    url: 'https://yle.fi/uutiset/3-11925581',
    imageId: '39-805993609d5f67656a5',
    publishedDate: '14.5.2021',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',

    title:
      'Tamperelainen, tule keskustelemaan kuntavaaleista Ylen Maailman suurimpaan vaalitelttaan – mukana myös asiantuntijoita',
    url: 'https://yle.fi/uutiset/3-11946063',
    imageId: '13-3-11952744',
    publishedDate: '31.5.2021',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      '7 nuoren elämä päättyi, kun panssarivaunu upposi järveen – pelastuneiden painajainen on kestänyt 30 vuotta: "En ole puhunut tästä oikeastaan kenellekään"',
    url: 'https://yle.fi/uutiset/3-11959451',
    imageId: '39-81020260ab875b143ef',
    publishedDate: '6.6.2021',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Kymmenen ihmistä asuu vakituisesti pienellä Aspön saarella keskellä Saaristomerta – Tore Johansson kertoo, millaista on elää karussa kodissa',
    url: 'https://yle.fi/uutiset/3-11969907',
    imageId: '39-81807960c0743f7558e',
    publishedDate: '12.6.2021',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data'],
    title: 'Näin posti kulkee – seurasimme kirjeiden matkaa 38 reitillä gps-lähettimillä',
    url: 'https://yle.fi/uutiset/3-11973043',
    imageId: '39-82300960cc9e87665f6',
    publishedDate: '21.6.2021',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data'],
    title:
      'Yle selvitti: Naiset ottivat aiempaa enemmän kuntapolitiikan huippupaikkoja – katso, ketkä käyttävät valtaa sinun kotikunnassasi',
    url: 'https://yle.fi/uutiset/3-12092060',
    imageId: '39-85135861389eb2d7b08',
    publishedDate: '10.9.2021',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Kummallinen kulkija tuli taloon, söi ja kuoli – perheeltään Ruotsissa mystisesti kadonnut mies eli kymmeniä vuosia ammattikulkurina Suomessa',
    url: 'https://yle.fi/uutiset/3-12144231',
    imageId: '39-86703761681e9387dbb',
    publishedDate: '16.10.2021',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Vuosikymmen sitten turkulaiset keksivät rakentaa hienon sillan, ja sen jälkeen kaikki mahdollinen meni pieleen: tämä on Logomon sillan tarina',
    url: 'https://yle.fi/uutiset/3-12110486',
    imageId: '39-838588610a6877035fa',
    publishedDate: '17.10.2021',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Ruoka kallistuu, kun ryhdymme maksamaan sen ilmastosynneistä – kokeile Ylen koneella, mitä kauppalaskullesi tapahtuu',
    url: 'https://yle.fi/uutiset/3-12193590',
    imageId: '39-88143461975460538ab',
    publishedDate: '19.11.2021',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',

    title:
      'Sinä äänestät, kuka päättää terveydenhoidostasi – lue 13 kysymystä ja vastausta, niin pääset kärryille tammikuun aluevaaleista',
    url: 'https://yle.fi/uutiset/3-12176668',
    imageId: '13-3-12207049',
    publishedDate: '30.11.2021',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['game'],
    title:
      'Teimme pelin, jota pelaamalla tiedät, mistä äänestämme aluevaaleissa – tai jos et tiedä, eliminoimme sinut',
    url: 'https://yle.fi/uutiset/3-12232988',
    imageId: '39-89907461d5adb3aa315',
    publishedDate: '11.1.2022',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Kokeile, miltä maailma näyttää näkövammaisen, pyörätuolilla liikkuvan ja hahmotushäiriöisen silmin',
    url: 'https://yle.fi/uutiset/3-12234621',
    imageId: '39-90182961e12ac1e4088',
    publishedDate: '15.1.2022',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['game'],
    title:
      'Rokotteista puhuminen päättyy herkästi jankkaamiseen, riitaan ja rikkoutuneisiin väleihin – onnistutko keskustelemaan botin kanssa kunnioittavasti?',
    url: 'https://yle.fi/uutiset/3-12302695',
    imageId: '39-914863620a3264b79aa',
    publishedDate: '15.2.2022',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Joseph ja Mohamed kaapattiin lapsena, ja heistä tehtiin hirviömäisiä sotilaita – nyt he ovat rikkinäisiä aikuisia, jotka katuvat tekojaan',
    url: 'https://yle.fi/uutiset/3-12360693',
    imageId: '39-9366296246c24828c94',
    publishedDate: '3.4.2022',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data'],
    title:
      'Mika Aaltolan perheessä on kolme harvinaista karvatonta terrieriä – katso, montako tietyn rotuista koiraa on kotipaikkakunnallasi',
    url: 'https://yle.fi/uutiset/3-12411117',
    imageId: '39-947451626a530f88821',
    publishedDate: '6.5.2022',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Vikkeläliikkeinen murhaaja sai nimensä hukuttamalla uhrinsa kanaliin, jonka pohjassa muhii nyt ikävä yllätys',
    url: 'https://yle.fi/uutiset/3-12511723',
    imageId: '13-3-12517618',
    publishedDate: '3.7.2022',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['game'],
    title:
      'Tässä pelissä kohtaat mahdottomia mukuloita ja kiukkuisia vanhempia – kokeile, selviätkö opettajana, terkkarina tai junnuvalmentajana',
    url: 'https://yle.fi/aihe/a/20-10003220',
    imageId: '39-1012807633187af00def',
    publishedDate: '1.10.2022',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['game'],
    title:
      'Mitä jos Linnan juhlat olisivat vaarassa peruuntua, ja kaikki olisi sinusta kiinni? Tässä pelissä valintasi ratkaisevat itsenäisyyspäivän kohtalon',
    url: 'https://yle.fi/aihe/a/20-10003769',
    imageId: '39-10407656385b40c8e6e5',
    publishedDate: '29.11.2022',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data'],
    title:
      'Ratikka imi kylkeensä pienen kaupungin verran ihmisiä – näin rakentaminen on mullistunut Tampereella',
    url: 'https://yle.fi/a/74-20017812',
    imageId: '39-107516863f34924775ca',
    publishedDate: '20.2.2023',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Kiersimme toriteltat, bileet ja tupaillat – kokeile, mihin päin Suomea Ylen vaalikaruselli sinut heittää',
    url: 'https://yle.fi/a/74-20024116',
    imageId: '39-10852176410d001491d4',
    publishedDate: '26.3.2023',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['game'],
    title:
      'Astu hoitajan kenkiin ja kokeile, miten pärjäät päivystyksen työvuorossa – tällaista on joutua valitsemaan potilaat, joita autat',
    url: 'https://yle.fi/a/74-20029828',
    imageId: '39-1108976645499805fa45',
    publishedDate: '9.5.2023',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title: 'Tällaista on elämä mäntynä – tutustu puun 700 vuoden elinkaareen monine seuralaisineen',
    url: 'https://yle.fi/a/74-20034378',
    imageId: '39-11238356479d3be128ad',
    publishedDate: '4.6.2023',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Kohdatessaan "vanhanaikaisia miesjohtajia" Iida-Amalia Nikkilä lyö pöytään armeijakortin – näin intin käyminen on auttanut naisia uralla',
    url: 'https://yle.fi/a/74-20034923',
    imageId: '39-112163964759d05f1714',
    publishedDate: '6.6.2023',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Kun näytös päättyy, jatkuu Karvon perheen asuntovaunuarki – tämä juttu kertoo siitä, mitä sirkuksen yleisö ei näe',
    url: 'https://yle.fi/a/74-20036927',
    imageId: '39-1130067648acc51786d0',
    publishedDate: '24.6.2023',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data'],
    title:
      'Harva tajuaa, että Helsingissä lähes kuka tahansa pääsee kesällä 26 saareen – katso kartalta kaikki saaret, reitit ja palvelut',
    url: 'https://yle.fi/a/74-20036843',
    imageId: '39-1136475649e758a95424',
    publishedDate: '2.7.2023',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data'],
    title:
      'Pyöräetu suosii hyväpalkkaista – katso laskurista, paljonko sinä hyötyisit työsuhdepyörästä',
    url: 'https://yle.fi/a/74-20045103',
    imageId: '39-115703664dba599c7971',
    publishedDate: '18.8.2023',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Nautitko jonottamisesta vai laittaako se kärsivällisyytesi koetukselle? Tämä juttu kertoo miksi',
    url: 'https://yle.fi/a/74-20045030',
    imageId: '39-115656164db100c6b55d',
    publishedDate: '18.8.2023',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data'],
    title:
      'Jarmo Saarela myy yksiötään 24 000 eurolla, mutta ketään ei kiinnosta – katso koneesta, paljonko omassa kunnassasi on tyhjiä asuntoja',
    url: 'https://yle.fi/a/74-20056571',
    imageId: '39-1187845652f8a5fb931e',
    publishedDate: '27.10.2023',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data'],
    title: 'Onnea valmistuneille! Katso koulunsa päättävien nimet Ylen valmistuneiden koneesta',
    url: 'https://yle.fi/a/74-20057938',
    imageId: '39-11968216549e8120dbd8',
    publishedDate: '9.11.2023',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data'],
    title:
      '”Tämä on ollut elämäntehtävä”, sanoo palkittu tutkija – katso Ylen koneesta, kuka sai omassa kunnassasi kunniamerkin',
    url: 'https://yle.fi/a/74-20062499',
    imageId: '39-12096406569c320197e7',
    publishedDate: '1.12.2023',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Miksi turvapaikanhakijat eivät vain kävele metsän läpi Suomeen? Tällaiset esteet Venäjä on rakentanut rajalle',
    url: 'https://yle.fi/a/74-20065026',
    imageId: '39-1217345658057c0131fd',
    publishedDate: '20.12.2023',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Jokainen presidenttiehdokas täytti ystäväkirjan – se paljastaa menneisyyden poikkeuksellisella tavalla',
    url: 'https://yle.fi/a/74-20069557',
    imageId: '39-1226690659fe96d57f12',
    publishedDate: '18.1.2024',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Komba Johnbull löysi timantin, jonka piti muuttaa Sierra Leonen tulevaisuus – jäljelle jäi vain pettymys',
    url: 'https://yle.fi/a/74-20074146',
    imageId: '39-124457165cddd58d4f5d',
    publishedDate: '17.2.2024',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      '20-vuotias Aarne Kokko kuoli asepalveluksessa – isä kysyy, miksi Puolustusvoimissa tapahtuu jatkuvasti onnettomuuksia',
    url: 'https://yle.fi/a/74-20080854',
    imageId: '39-125506865eaf0fa27766',
    publishedDate: '1.4.2024',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Nyt yleistyy trendi, että suomen kielellä ei saa palvelua – testaa, millainen kielitaito riittää eri ammateissa',
    url: 'https://yle.fi/a/74-20079949',
    imageId: '39-125379565e826e03a6b4',
    publishedDate: '3.4.2024',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['game'],
    title:
      'Suomen hallitus haluaa säästää kolme miljardia euroa ja äkkiä – leikkaa itse ja päätä, kuka kärsii',
    url: 'https://yle.fi/a/74-20082596',
    imageId: '39-12690406617b28c2ff6d',
    publishedDate: '12.4.2024',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Tarkistimme faktoja EU:sta vuosien varrelta – kokeile tiedätkö, mikä on totta ja mikä tarua',
    url: 'https://yle.fi/a/74-20084891',
    imageId: '39-1291567665438c111525',
    publishedDate: '2.6.2024',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data'],
    title:
      'Tämä juttu kumoaa yleisen uskomuksen liikenneonnettomuuksista – katso, liikutko itse riskiteillä',
    url: 'https://yle.fi/a/74-20091408',
    imageId: '39-130169866695279a6530',
    publishedDate: '17.6.2024',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['game'],
    title:
      'Trump solvaa siirtolaisia mielisairaiksi ja terroristeiksi – lähde Texasiin ja selvitä, mitä rajalla tapahtuu',
    url: 'https://yle.fi/a/74-20116511',
    imageId: '39-13733196724abf14efad',
    publishedDate: '13.10.2024',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['game'],
    title:
      'Kokeile, millaista on hakea mielenterveysapua – huonolla tuurilla pääset vain päivystyksen kautta kotiin',
    url: 'https://yle.fi/a/74-20119762',
    imageId: '39-136735767179e9c9fe84',
    publishedDate: '26.10.2024',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title:
      'Yle sai ennen julkaisemattomia tietoja kadonneen Raisa Räisäsen ja paloittelumurhaajan yhteydestä',
    url: 'https://yle.fi/a/74-20120185',
    imageId: '39-1369394671b66f14abca',
    publishedDate: '27.10.2024',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data'],
    title:
      'Iso osa kasi- ja ysiluokkalaisista jättää kouluruoan kokonaan väliin – katso, mitä he syövät oikeasti',
    url: 'https://yle.fi/a/74-20076403',
    imageId: '39-125313165e5f4b7ac60a',
    publishedDate: '5.3.2024',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data'],
    title:
      'Oulun Kaukovainio -37 %, Helsingin Puistola -25 % – katso oman postinumeroalueesi asuntokaupan tilanne ja vertaa muihin',
    url: 'https://yle.fi/a/74-20040520',
    imageId: '39-113966864a7e718ba30a',
    publishedDate: '14.7.2023',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['feature'],
    title: 'Tampereen rohkea kasvuloikka jätti tuumivan Turun kauas taakseen',
    url: 'https://yle.fi/a/74-20040125',
    imageId: '39-11268106481c6570acc1',
    publishedDate: '9.7.2023',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data'],
    title:
      'Espoossa on “tavallinen” lukio, johon pyrkivät nyt vimmatusti nuoret ja opettajat – näin hyvän kierre saatiin aikaan',
    url: 'https://yle.fi/a/74-20036932',
    imageId: '39-1130469648b0ff775259',
    publishedDate: '16.6.2023',
    publisher: 'Yle',
    roles: ['coder'],
  },
  {
    platform: 'web',
    types: ['data'],
    title:
      'Katso koneesta, kuinka paljon terveys- ja sosiaalipalvelujen asiakasmaksut ovat nousseet kotikunnassasi',
    url: 'https://yle.fi/a/74-20031860',
    imageId: '39-1116247646760434cf1a',
    publishedDate: '22.5.2023',
    publisher: 'Yle',
    roles: ['coder'],
  },
];

export default articles;
